ALTER TABLE branches ADD COLUMN email VARCHAR(100) DEFAULT NULL AFTER maps;
ALTER TABLE branches ADD COLUMN phone VARCHAR(100) DEFAULT NULL AFTER email;
ALTER TABLE branches ADD COLUMN pic VARCHAR(100) DEFAULT NULL AFTER phone;